### ISSUE TITLE
leveldb.maxopenfiles is not respected

### ISSUE THREAD

**Issue by bensmrs** [senx/warp10-platform#1059]
Hi,
When starting Warp 10, I get the following error:
```
  ___       __                           ____________
  __ |     / /_____ _______________      __<  /_  __ \
  __ | /| / /_  __ `/_  ___/__  __ \     __  /_  / / /
  __ |/ |/ / / /_/ /_  /   __  /_/ /     _  / / /_/ /
  ____/|__/  \__,_/ /_/    _  .___/      /_/  \____/
                           /_/

  Revision 2.9.0

2022-01-19 18:54:11.714:INFO:iwsjoejs.AbstractConnector:Started SelectChannelConnector@127.0.0.1:37147
2022-01-19T18:54:11,716 main INFO  store.Constants - ########[ Initialized with 1000 time units per millisecond ]###
#####
2022-01-19T18:54:11,725 main WARN  script.WarpFleetMacroRepository - No validator macro, default macro will reject a
ll URLs.
REPORT secret not set, using '1c77f05b-8aee-4328-a503-6d2363fefcf0'.
Exception in thread "main" java.lang.RuntimeException: org.fusesource.leveldbjni.internal.NativeDB$DBException: IO e
rror: /srv/warp10/leveldb/14939849.sst: Trop de fichiers ouverts
        at org.fusesource.leveldbjni.internal.JniDBIterator.seek(JniDBIterator.java:68)
        at io.warp10.standalone.WarpDB$WarpIterator.seek(WarpDB.java:133)
        at io.warp10.standalone.StandaloneDirectoryClient.<init>(StandaloneDirectoryClient.java:193)
        at io.warp10.standalone.Warp.main(Warp.java:379)
Caused by: org.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: /srv/warp10/leveldb/14939849.sst: Trop
 de fichiers ouverts
        at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200)
        at org.fusesource.leveldbjni.internal.NativeIterator.checkStatus(NativeIterator.java:121)
        at org.fusesource.leveldbjni.internal.NativeIterator.seek(NativeIterator.java:151)
        at org.fusesource.leveldbjni.internal.NativeIterator.seek(NativeIterator.java:145)
        at org.fusesource.leveldbjni.internal.NativeIterator.seek(NativeIterator.java:138)
        at org.fusesource.leveldbjni.internal.JniDBIterator.seek(JniDBIterator.java:63)
        ... 3 more
2022-01-19T18:54:52,999 main INFO  store.Constants - ########[ Initialized with 1000 time units per millisecond ]########
2022-01-19T18:54:53,009 main WARN  script.WarpFleetMacroRepository - No validator macro, default macro will reject all URLs.
2022-01-19 18:54:54.427:INFO:iwsjoejs.Server:jetty-8.y.z-SNAPSHOT
```

It says that I have too many files open. However I set my `leveldb.maxopenfiles` (nothing, 1k, 100k…), Warp 10 opens 524287 files and then dies (found in a pretty dirty way: `while true; do for pid in [0-9]*; do ls /proc/$pid/fd/ | wc -l; done | grep ......; done`). My soft `ulimit` is 1024 and my hard `ulimit` is 1048576 (twice the number of files after which Warp 10 crashes). What can I do to properly start Warp 10?

Thanks in advance

**Comment by bensmrs** [comment]
The problem only appears when launching Warp10 with its unit file. When using the warp10 user, the problem does not appear.

**Comment by hbs** [comment]
How many SST files are there in the leveldb directory? Looks like Warp 10 attempted to redispatch the SST files because it did not have access to the MANIFEST file, this hypothesis would be confirmed if the number of SST files is around 500k.

**Comment by bensmrs** [comment]
There are 280224 files.
I ran a leveldb repair a few hours ago. Also, when running Warp 10 with the warp10 user, two CPU cores are maxed out and Warp 10 doesn’t open its HTTP port (I waited for a few hours and it seems stuck), that also happened right after the repair. Maybe it is repair related and I should rename the issue?

**Comment by bensmrs** [comment]
Hmmm I think I start to see the problem: `Compacting 280212@0 + 0@1 files`.

**Comment by hbs** [comment]
Yes, LevelDB repair is a process which scans all the SST files to determine the start and end keys of each one then puts them all at level 0. The next time LevelDB is open compactions will kick in which will attempt to ventilate the SST files in further levels.

**Comment by bensmrs** [comment]
Damn… The compaction seems extremely slow (20k keys every 10 minutes), and I have like 400GB of data. Any tips on how to speed up the process (if it is even possible)?
To get back to the original message, LevelDB tries to open more files than allowed (actually, it seems that it opens the same file several times). Is it only the case during the compaction phase?

**Comment by hbs** [comment]
The max open files is simply for the normal operations of LevelDB. For compactions it has to open at least N + 1 files when compacting N files.

I've sent you an email asking for you MANIFEST file.
